services:
  adguardhome-sync:
    image: lscr.io/linuxserver/adguardhome-sync
    container_name: adguardhome-sync
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TIMEZONE:-Etc/UTC}
      - CONFIGFILE=/config/adguardhome-sync.yaml
      - ADGUARDHOME_PASSWORD=${ADGUARDHOME_PASSWORD}
    volumes:
      - ${ADGUARDHOMESYNC_CONFIG_FOLDER:-./config}:/config
      - ./adguardhome-sync.yaml:/config/adguardhome-sync.yaml
    ports:
      - ${ADGUARDHOMESYNC_PORT:-8080}:8080
    restart: unless-stopped
    networks:
      local:
        ipv4_address: 172.${SUBNET_NUMBER:-20}.0.2

networks:
  local:
    name: adguardhome_sync-local-network
    ipam:
      config:
        - subnet: 172.${SUBNET_NUMBER:-20}.0.0/16